feat: add terraform validate job

diff --git a/.github/workflows/action-terraform-verify.yml b/.github/workflows/action-terraform-verify.yml
--- a/.github/workflows/action-terraform-verify.yml
+++ b/.github/workflows/action-terraform-verify.yml
@@ -1,4 +1,4 @@
-name: Validate terraform fmt
+name: Validate terraform fmt and validate
 
 on:
   pull_request:
@@ -11,7 +11,7 @@ permissions:
   contents: read
 
 jobs:
-  validate:
+  terraform_fmt:
     runs-on: ubuntu-latest
     name: terraform fmt check
     outputs:
@@ -34,14 +34,39 @@ jobs:
 
       - name: Validate terraform fmt (added_modified)
         run: |
-          set -e
+          set +e
+          echo "CHECK_STATUS=0" >> $GITHUB_ENV
           for changed_file in ${{ steps.pr_files.outputs.added_modified }}; do
+            echo "Checking terraform fmt on ${changed_file}..."
             if [[ $changed_file == *.tf ]]; then
-              echo "Checking terraform fmt on ${changed_file}..."
               terraform fmt -check $changed_file
+              FMT_STATUS=$?
+              if [[ $FMT_STATUS -ne 0 ]]; then
+                echo "❌ terraform fmt failed - ${changed_file}" >> $GITHUB_STEP_SUMMARY
+                echo "CHECK_STATUS=1" >> $GITHUB_ENV
+              fi
             fi
           done
 
       - name: Process check
         if: always()
         run: exit $CHECK_STATUS
+
+  terraform_validate:
+    runs-on: ubuntu-latest
+    name: terraform validate check
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v2
+        with:
+          terraform_version: 1.2.4
+
+      - name: Initialize Terraform
+        run: terraform init
+        working-directory: ./infrastructure
+
+      - name: Validate Terraform configuration
+        run: terraform validate
+        working-directory: ./infrastructure
